# Site settings
title: Robin Bayliss
description: "The official website for romance author Robin Bayliss and her Snowball Falls Series."
url: "https://needscoffee.github.io" # Your main domain
baseurl: "/snowfall" # The name of your repository

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Sass settings
sass:
  sass_dir: assets/css
  style: compressed
